# Generated by Django 2.2.4 on 2019-11-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='img_src',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
